/*****************************************************************************
 * File generated by HDevelop for HALCON/C Version 23.11.0.0
 * Non-ASCII strings in this file are encoded in local-8-bit encoding (cp936).
 * Ensure that the interface encoding is set to locale encoding by calling
 * SetHcInterfaceStringEncodingIsUtf8(FALSE) at the beginning of the program.
 * 
 * Please note that non-ASCII characters in string constants are exported
 * as octal codes in order to guarantee that the strings are correctly
 * created on all systems, independent on any compiler settings.
 * 
 * Source files with different encoding should not be mixed in one project.
 *****************************************************************************/

#include "HalconC.h"
#include "halconc/Hdevthread.h"



/* Chapter: Develop*/
/* Short Description: Switch dev_update_pc, dev_update_var, and dev_update_window to 'off'. */
void dev_update_off ()
{
  /* Stack for temporary tuples */
  Htuple   TTemp[100];
  int      SP=0;
  /* Stack for temporary tuple vectors */
  Hvector  TVTemp[100] = {0};
  int      SPTV=0;

  /****************************************************/
  /******************   Begin procedure   *************/
  /****************************************************/

  /*This procedure sets different update settings to 'off'.*/
  /*This is useful to get the best performance and reduce overhead.*/
  /**/
  /* dev_update_pc(...); only in hdevelop*/
  /* dev_update_var(...); only in hdevelop*/
  /* dev_update_window(...); only in hdevelop*/
  /*========== return ==========*/

  /* Clear temporary tuple stack */
  while (SP > 0)
    destroy_tuple(TTemp[--SP]);
  /* Clear temporary tuple vectors stack*/
  while (SPTV > 0)
    V_destroy_vector(TVTemp[--SPTV]);
  return;

  /****************************************************/
  /******************     End procedure   *************/
  /****************************************************/

}
